/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/eIeYSoSkLrk
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"

export function Slider() {
  return (
    <Carousel className="w-full max-w-4xl mx-auto">
      <CarouselContent>
        <CarouselItem>
          <div className="grid grid-cols-4 gap-4 p-4">
            <Card>
              <CardHeader>
                <CardTitle>Drug A</CardTitle>
              </CardHeader>
              <CardContent>
                <p>This is a brief description of Drug A.</p>
              </CardContent>
              <img
                alt="Drug A"
                className="w-24 h-24 object-cover"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100"
              />
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Drug B</CardTitle>
              </CardHeader>
              <CardContent>
                <p>This is a brief description of Drug B.</p>
              </CardContent>
              <img
                alt="Drug B"
                className="w-24 h-24 object-cover"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100"
              />
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Drug C</CardTitle>
              </CardHeader>
              <CardContent>
                <p>This is a brief description of Drug C.</p>
              </CardContent>
              <img
                alt="Drug C"
                className="w-24 h-24 object-cover"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100"
              />
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Drug D</CardTitle>
              </CardHeader>
              <CardContent>
                <p>This is a brief description of Drug D.</p>
              </CardContent>
              <img
                alt="Drug D"
                className="w-24 h-24 object-cover"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100"
              />
            </Card>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="grid grid-cols-4 gap-4 p-4">
            <Card>
              <CardHeader>
                <CardTitle>Drug E</CardTitle>
              </CardHeader>
              <CardContent>
                <p>This is a brief description of Drug E.</p>
              </CardContent>
              <img
                alt="Drug E"
                className="w-24 h-24 object-cover"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100"
              />
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Drug F</CardTitle>
              </CardHeader>
              <CardContent>
                <p>This is a brief description of Drug F.</p>
              </CardContent>
              <img
                alt="Drug F"
                className="w-24 h-24 object-cover"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100"
              />
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Drug G</CardTitle>
              </CardHeader>
              <CardContent>
                <p>This is a brief description of Drug G.</p>
              </CardContent>
              <img
                alt="Drug G"
                className="w-24 h-24 object-cover"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100"
              />
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Drug H</CardTitle>
              </CardHeader>
              <CardContent>
                <p>This is a brief description of Drug H.</p>
              </CardContent>
              <img
                alt="Drug H"
                className="w-24 h-24 object-cover"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100"
              />
            </Card>
          </div>
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious />
      <CarouselNext />
    </Carousel>
  )
}
